### ISSUE TITLE
Change status bar color to match content

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/dpm#12]
Currently it appears that the app is using the same status bar color (grey) for all screens. Instead, from what I can see from the UI the color should change based on the content of the page. 

Expected
<img width="300" src="https://user-images.githubusercontent.com/9119016/138404796-31042175-2ead-4474-885d-05d40625eb2f.png" />
<img width="300" src="https://user-images.githubusercontent.com/9119016/138404793-496630f6-9382-43c3-9227-a084b6ef267c.png" />

Actual
<img width="300" src="https://user-images.githubusercontent.com/9119016/138404797-f0fd1b3c-94c1-4fdb-b402-81bd3766b5c3.png" />
<img width="300" src="https://user-images.githubusercontent.com/9119016/138404794-fc9057b8-2c78-4d4d-ad27-6ea9071792f0.png" />

**Comment by manu0466** [comment]
This has been fixed with eb8075dd and 93c0d690
