### ISSUE TITLE
Cannot upload image

### ISSUE THREAD

**Issue by dadamu** [desmos-labs/dpm#39]
![image](https://user-images.githubusercontent.com/26020018/143555630-6551723b-0c06-4718-ac82-235694eeef07.png)
Creating the profile with imgs on dpm can't work properly.

**Comment by manu0466** [comment]
Tried to reach out to the peoples that had this issue on Discord but didn't get any feedback.
I have test this on bot iOS and Android and the profile/cover picture upload is working. I supose that our IPF node went down during the Airdrop causing this error message.
