### ISSUE TITLE
dpm not working on ios

### ISSUE THREAD

**Issue by manu0466** [desmos-labs/dpm#58]
When starting DPM on iOS on metro is displayed the following error:
```
ERROR  TypeError: _reactNativeSensitiveInfo.default.hasEnrolledFingerprints is not a function. (In '_reactNativeSensitiveInfo.default.hasEnrolledFingerprints()', '_reactNativeSensitiveInfo.default.hasEnrolledFingerprints' is undefined)
ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

**Comment by ale-mazz** [comment]
@manu0466 did you try to `pod install` ?

**Comment by manu0466** [comment]
Yes, I tried several times with @bragaz  and is not working.
We also tried rolling back to the v1.0.7 tag and at that version the application is working properly.

**Comment by ale-mazz** [comment]
To test it and fix it I will need to have a Mac OS system (end of this month) meanwhile we can meet up with @bragaz later next week to sort it out if you want

**Comment by bragaz** [comment]
@manu0466 What do you think? In my opinion I would avoid any kind of test on the master branch and proceed as follow:
1. A revert of the master before the refactoring (Aligning it to the last tagged version that works on iOS);
2. A new branch with the refactoring changes;
3. Add an iOS workflow to test the build when PRs are made;
4. Look for a solution of the problem.

**Comment by manu0466** [comment]
@bragaz I agree that we should try to isolate the problem on a new branch and add an action to test the build on PR, but
unfortunaly in this case the problem seems to arise at runtime and without a test on a device is hard to find the cause.
To avoid to have also you on a call since we are not planning a new release in this month we can wait for the Mac of @ale-mazz to arrive and then I will follow the issue with him.
