### ISSUE TITLE
Broken bluetooth connection in iOS

### ISSUE THREAD

**Issue by bragaz** [desmos-labs/dpm#92]
I was testing the application login with my ledger nano X and found out that it's not working anymore.
What happens is that the ledger freezes on the "confirm pairing" screen and the app show a "disconnected device" error.

Step to reproduce:
1. Open DPM on iOS 
2. Try to import account with ledger nano X

![IMG_4904](https://user-images.githubusercontent.com/26248202/174762062-4cf7ced6-7ff7-4577-a656-a4a82964c556.PNG)

![IMG_4905](https://user-images.githubusercontent.com/26248202/174762161-d9d23ed3-0f1d-4e1c-a171-85532ab9c1a8.jpg)

**Comment by bragaz** [comment]
cc @manu0466

**Comment by ale-mazz** [comment]
Hi Leo, I tried several times to reproduce the error but could not.
I am using an iPhone X with the latest version of iOS and a Ledger Nano X. My version of DPM is 1.13

**Comment by bragaz** [comment]
@ale-mazz Is it working for you? I'll delete and re download the app and try again then

**Comment by ale-mazz** [comment]
@bragaz Yes for me its working!
